 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/withdrawals", type: :request do
  
  # Withdrawal. As you add validations to Withdrawal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Withdrawal.create! valid_attributes
      get withdrawals_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      withdrawal = Withdrawal.create! valid_attributes
      get withdrawal_url(withdrawal)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_withdrawal_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      withdrawal = Withdrawal.create! valid_attributes
      get edit_withdrawal_url(withdrawal)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Withdrawal" do
        expect {
          post withdrawals_url, params: { withdrawal: valid_attributes }
        }.to change(Withdrawal, :count).by(1)
      end

      it "redirects to the created withdrawal" do
        post withdrawals_url, params: { withdrawal: valid_attributes }
        expect(response).to redirect_to(withdrawal_url(Withdrawal.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Withdrawal" do
        expect {
          post withdrawals_url, params: { withdrawal: invalid_attributes }
        }.to change(Withdrawal, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post withdrawals_url, params: { withdrawal: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested withdrawal" do
        withdrawal = Withdrawal.create! valid_attributes
        patch withdrawal_url(withdrawal), params: { withdrawal: new_attributes }
        withdrawal.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the withdrawal" do
        withdrawal = Withdrawal.create! valid_attributes
        patch withdrawal_url(withdrawal), params: { withdrawal: new_attributes }
        withdrawal.reload
        expect(response).to redirect_to(withdrawal_url(withdrawal))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        withdrawal = Withdrawal.create! valid_attributes
        patch withdrawal_url(withdrawal), params: { withdrawal: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested withdrawal" do
      withdrawal = Withdrawal.create! valid_attributes
      expect {
        delete withdrawal_url(withdrawal)
      }.to change(Withdrawal, :count).by(-1)
    end

    it "redirects to the withdrawals list" do
      withdrawal = Withdrawal.create! valid_attributes
      delete withdrawal_url(withdrawal)
      expect(response).to redirect_to(withdrawals_url)
    end
  end
end
